name: CI Pipeline

on: 
    workflow_call:

jobs:
  setup-and-test:
    runs-on: ${{ vars.RUNNER_LABEL || 'arc-runner-set-eks' }}

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Cache Python dependencies for both environments (Spark + Airflow)
      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.virtualenvs
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-build.txt', '**/requirements-spark.txt', '**/requirements-airflow.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Set up Python environment for Spark
      - name: Set up Python for Spark
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use your desired Python version

      - name: Install Spark dependencies
        run: |
          python -m venv $HOME/spark_env
          $HOME/spark_env/bin/python -m pip install --upgrade pip
          $HOME/spark_env/bin/python -m pip install --no-cache-dir --index-url http://internal-pypi-server-alb-9235208.eu-west-1.elb.amazonaws.com/simple/ -r requirements-spark.txt
          $HOME/spark_env/bin/python -m pip install pytest  # Install pytest in the Spark environment

      # Set up Python environment for Airflow
      - name: Set up Python for Airflow
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Airflow dependencies
        run: |
          python -m venv $HOME/airflow_env
          $HOME/airflow_env/bin/python -m pip install --upgrade pip
          $HOME/airflow_env/bin/python -m pip install --no-cache-dir "apache-airflow[amazon]==2.4.2" \
            -c https://raw.githubusercontent.com/invent-analytics/airflow-constraints/main/2.4.2/constraints-3.8.txt
          $HOME/airflow_env/bin/python -m pip install --no-cache-dir --index-url http://internal-pypi-server-alb-9235208.eu-west-1.elb.amazonaws.com/simple/ -r requirements-airflow.txt
          $HOME/airflow_env/bin/python -m pip install pytest  # Install pytest in the Airflow environment

      # Run tests for Spark environment
      - name: Run Spark tests
        run: |
          . $HOME/spark_env/bin/activate
          # Run Spark-specific tests (adjust this according to your test commands)
          pytest tests/spark_tests/  # Adjust this to match your test folder

      # Run tests for Airflow environment
      - name: Run Airflow tests
        run: |
          . $HOME/airflow_env/bin/activate
          # Run Airflow-specific tests (adjust this according to your test commands)
          pytest tests/airflow_tests/  # Adjust this to match your test folder
